### ISSUE TITLE
QQ群无法加入

### ISSUE THREAD

**Issue by manhere** [bwenquan/QuanAuth#17]
RT

**Comment by bwenquan** [comment]
我已检查：
+ 群信用星级无问题
+ 群已开启公开查找
+ 可以通过群号查找到群
+ 群验证中无等待处理的申请


请您检查：
+ 群号是否输入正确
+ 账号是否风险\敏感账号
+ 账号是否被TX风控无法加群

如有问题您可以咨询腾讯QQ客服 https://kf.qq.com 。

**Comment by manhere** [comment]
加群问题答案是什么。。。

**Comment by manhere** [comment]
solved
