### ISSUE TITLE
vaptcha 一直显示 启动中...

### ISSUE THREAD

**Issue by TomyJan** [bwenquan/QuanAuth#3]
经本小白测试, 是由于 vaptcha 更新(了版本号) 以及 cdn 服务器变更导致无法加载 js

目前可行的解决方案:
分别将以下行中 https://cdn.vaptcha.com/v2.js 替换为 https://v-cn.vaptcha.com/v3.js

1.  ./admin/login.html 第 12 行 
2.  ./agent/login.html 第 12 行 
3.  ./ajax.php 第 102 645 行 
4.  ./auth.php 第 14 行 
5.  ./change.php 第 14 行 
6.  ./openagent.php   第 14 行 
7.  ./query.php 第 14 行 

如果懒得修改又想用 vaptcha , 可以直接下载我修改好的:
https://pan.tomys.top/s/EOI9
(Update 打头为升级包, 仅包含受影响文件; All 打头为全量包, 包含修改后的整个程序)

另, 感谢大佬开源!!!

**Comment by TomyJan** [comment]
> 经本小白测试, 是由于 vaptcha 更新(了版本号) 以及 cdn 服务器变更导致无法加载 js
> 
> 目前可行的解决方案:
> 分别将以下行中 https://cdn.vaptcha.com/v2.js 替换为 https://v-cn.vaptcha.com/v3.js
> 
> 1. ./admin/login.html 第 12 行
> 2. ./agent/login.html 第 12 行
> 3. ./ajax.php 第 102 645 行
> 4. ./auth.php 第 14 行
> 5. ./change.php 第 14 行
> 6. ./openagent.php   第 14 行
> 7. ./query.php 第 14 行
> 
> 如果懒得修改又想用 vaptcha , 可以直接下载我修改好的:
> https://pan.tomys.top/s/EOI9
> (Update 打头为升级包, 仅包含受影响文件; All 打头为全量包, 包含修改后的整个程序)
> 
> 另, 感谢大佬开源!!!

不行===能验证过去但是回调不对吧?
没本事了,等大佬修好再用

**Comment by bwenquan** [comment]
#13 已修复

**Comment by TomyJan** [comment]
> #13 已修复

好耶!感谢大佬,这就去测试
